// Code generated by tools/apitypes from .api contract. DO NOT EDIT.
// 生成物入库（CI diff 阻断，02 §12.5）；改契约 → 重生成 → diff 干净。

export interface AuditLogItem {
	log_id: string;
	trace_id: string;
	uid: string;
	action: string;
	target_type: string;
	target_id: string;
	before_json: string;
	after_json: string;
	result: string;
	client: string;
	on_behalf_of: string;
	created_at: number;
}

export interface AuditLogListReq {
	page: number;
	size: number;
	action?: string;
	uid?: string;
	target_type?: string;
	target_id?: string;
}

export interface AuditLogListResp {
	list: AuditLogItem[];
	total: number;
}

export interface BomItem {
	sku_id: string;
	sku_name: string;
	qty: number;
}

export interface ClaimApproveReq {
	claim_no: string;
	approve: boolean;
	remark?: string;
}

export interface ClaimCreateReq {
	warranty_id: string;
	type: string;
	description?: string;
}

export interface ClaimCreateResp {
	claim_id: string;
	claim_no: string;
}

export interface ClaimListReq {
	status?: string;
	page?: number;
	size?: number;
}

export interface ClaimListResp {
	list: ClaimView[];
	total: number;
}

export interface ClaimNoPath {
	claim_no: string;
}

export interface ClaimSettleReq {
	claim_no: string;
	settle_type: string;
	amount?: string;
}

export interface ClaimView {
	claim_no: string;
	warranty_id: string;
	warranty_no: string;
	type: string;
	description: string;
	status: string;
	settle_type: string;
	amount: string;
	created_at: number;
}

export interface CmdAuditItem {
	cmd_audit_id: string;
	cmd_id: string;
	sn: string;
	uid: string;
	action: string;
	payload_json: string;
	result: string;
	error: string;
	trace_id: string;
	created_at: number;
}

export interface CmdAuditListReq {
	page: number;
	size: number;
	sn?: string;
	cmd_id?: string;
}

export interface CmdAuditListResp {
	list: CmdAuditItem[];
	total: number;
}

export interface CmdListReq {
	device_id?: string;
	sn?: string;
	status?: string;
	page?: number;
	size?: number;
}

export interface CmdListResp {
	list: CmdView[];
	total: number;
}

export interface CmdSendReq {
	device_id?: string;
	sn?: string;
	cmd_type: string;
	params_json?: string;
	client_cmd_id?: string;
}

export interface CmdSendResp {
	cmd_id: string;
}

export interface CmdView {
	cmd_id: string;
	device_id: string;
	sn: string;
	cmd_type: string;
	params_json: string;
	status: string;
	retry_count: number;
	acked_at: number;
	fail_reason: string;
	operator: string;
	created_at: number;
}

export interface ContactCreateReq {
	id: string;
	name: string;
	mobile: string;
	position?: string;
	is_default?: boolean;
	notify_pref?: string;
}

export interface ContactItem {
	contact_id: string;
	party_id: string;
	name: string;
	mobile: string;
	position: string;
	is_default: boolean;
	notify_pref: string;
	created_at: number;
}

export interface ContactListResp {
	list: ContactItem[];
}

export interface ContractArchiveReq {
	contract_no: string;
	action: string;
	remark?: string;
}

export interface ContractFileUploadReq {
	contract_no: string;
	file_id: string;
	file_name: string;
	sign_party_name?: string;
	sign_party_type?: string;
	remark?: string;
}

export interface ContractFileUploadResp {
	version: number;
}

export interface ContractFileView {
	file_rec_id: string;
	file_id: string;
	file_name: string;
	version: number;
	sign_party_name: string;
	sign_party_type: string;
	status: string;
	uploaded_by: string;
	uploader_name: string;
	uploaded_at: number;
	remark: string;
}

export interface ContractListReq {
	keyword?: string;
	type?: string;
	status?: string;
	page?: number;
	size?: number;
}

export interface ContractListResp {
	list: ContractView[];
	total: number;
}

export interface ContractNoPath {
	contract_no: string;
}

export interface ContractView {
	contract_id: string;
	contract_no: string;
	type: string;
	status: string;
	name: string;
	template_id: string;
	amount: string;
	files: ContractFileView[];
	effective_at: number;
	archived_at: number;
	remark: string;
	created_at: number;
	created_by: string;
}

export interface CrmRecordCreateReq {
	id: string;
	content: string;
	next_follow_at?: number;
}

export interface CrmRecordItem {
	record_id: string;
	party_id: string;
	content: string;
	next_follow_at: number;
	created_by: string;
	created_at: number;
}

export interface CrmRecordListResp {
	list: CrmRecordItem[];
}

export interface DealerExtItem {
	party_id: string;
	dealer_level: string;
	authorized_region: string;
	rebate_rule: string;
	updated_at: number;
}

export interface DealerExtResp {
	dealer_ext: DealerExtItem;
}

export interface DealerExtUpsertReq {
	id: string;
	dealer_level?: string;
	authorized_region?: string;
	rebate_rule?: string;
}

export interface DeviceActivateReq {
	device_id: string;
	party_id?: string;
}

export interface DeviceGetResp {
	device: DeviceView;
}

export interface DeviceImportItem {
	sn: string;
	product_key: string;
	model?: string;
	batch_no?: string;
}

export interface DeviceImportReq {
	items: DeviceImportItem[];
	provision?: boolean;
}

export interface DeviceImportResp {
	imported: number;
	secrets: DeviceSecretRow[];
	provision_errors: string[];
}

export interface DeviceListReq {
	keyword?: string;
	status?: string;
	product_key?: string;
	page?: number;
	size?: number;
}

export interface DeviceListResp {
	list: DeviceView[];
	total: number;
}

export interface DeviceNoPath {
	device_id: string;
}

export interface DeviceProvisionResp {
	sn: string;
	secret: string;
}

export interface DeviceSecretRow {
	sn: string;
	secret: string;
}

export interface DeviceShadowMetric {
	key: string;
	value: number;
}

export interface DeviceShadowResp {
	sn: string;
	ts: number;
	metrics: DeviceShadowMetric[];
	raw: string;
}

export interface DeviceStationResp {
	station_id: string;
	station_no: string;
	station_name: string;
	role: string;
}

export interface DeviceTopologyNode {
	node_id: string;
	parent_id: string;
	node_type: string;
	node_name: string;
	sort: number;
}

export interface DeviceTopologyResp {
	nodes: DeviceTopologyNode[];
}

export interface DeviceTopologySaveNode {
	parent_ref: number;
	node_type: string;
	node_name?: string;
	sort?: number;
}

export interface DeviceTopologySaveReq {
	device_id: string;
	nodes: DeviceTopologySaveNode[];
}

export interface DeviceTopologySaveResp {
	saved: number;
}

export interface DeviceTransitionReq {
	device_id: string;
	to_status: string;
	reason?: string;
}

export interface DeviceView {
	device_id: string;
	sn: string;
	product_key: string;
	model: string;
	batch_no: string;
	status: string;
	party_id: string;
	order_no: string;
	activated_at: number;
	has_secret: boolean;
	created_at: number;
}

export interface ExtensionNoPath {
	extension_no: string;
}

export interface ExtensionRefundReq {
	extension_no: string;
	reason?: string;
}

export interface ExtensionSellReq {
	base_warranty_id: string;
	months: number;
	order_no?: string;
	amount?: string;
}

export interface ExtensionSellResp {
	extension_id: string;
	extension_no: string;
}

export interface ExtensionTransferReq {
	extension_no: string;
	to_target_type: string;
	to_target_id?: string;
	to_target_key?: string;
}

export interface FirmwareListReq {
	product_key?: string;
	page?: number;
	size?: number;
}

export interface FirmwareListResp {
	list: FirmwareView[];
	total: number;
}

export interface FirmwareSaveReq {
	product_key: string;
	version: string;
	file_url: string;
	file_size?: number;
	sha256: string;
	signature: string;
	remark?: string;
}

export interface FirmwareSaveResp {
	firmware_id: string;
}

export interface FirmwareView {
	firmware_id: string;
	product_key: string;
	version: string;
	file_url: string;
	file_size: number;
	sha256: string;
	sign_alg: string;
	remark: string;
	created_at: number;
}

export interface IDPath {
	id: string;
}

export interface InventoryItem {
	inventory_id: string;
	warehouse_id: string;
	sku_id: string;
	available: number;
	locked: number;
	in_transit: number;
	defective: number;
	low_stock_threshold: number;
	updated_at: number;
}

export interface InventoryListReq {
	page: number;
	size: number;
	warehouse_id?: string;
	sku_id?: string;
	low_only?: boolean;
}

export interface InventoryListResp {
	list: InventoryItem[];
	total: number;
}

export interface InvoiceCreateReq {
	payment_no: string;
	title: string;
	tax_no?: string;
	amount?: string;
}

export interface InvoiceCreateResp {
	invoice_no: string;
}

export interface InvoiceListReq {
	keyword?: string;
	status?: string;
	page?: number;
	size?: number;
}

export interface InvoiceListResp {
	list: InvoiceView[];
	total: number;
}

export interface InvoiceNoPath {
	invoice_no: string;
}

export interface InvoiceReverseReq {
	invoice_no: string;
	reason?: string;
}

export interface InvoiceView {
	invoice_no: string;
	payment_no: string;
	order_no: string;
	title: string;
	tax_no: string;
	amount: string;
	status: string;
	reverse_reason: string;
	issued_at: number;
	created_at: number;
}

export interface LoginReq {
	mobile: string;
	password: string;
}

export interface LoginResp {
	tokens: TokenPair;
	uid: string;
	nickname: string;
}

export interface MeResp {
	uid: string;
	nickname: string;
	mobile: string;
	tenant_id: string;
	roles: string[];
	perms: string[];
	data_scope: string;
}

export interface MenuCreateReq {
	parent_id?: string;
	name: string;
	type: number;
	perm_code?: string;
	path?: string;
	icon?: string;
	sort?: number;
}

export interface MenuItem {
	menu_id: string;
	parent_id: string;
	name: string;
	type: number;
	perm_code: string;
	path: string;
	icon: string;
	sort: number;
	status: number;
}

export interface MenuListResp {
	list: MenuItem[];
}

export interface MenuUpdateReq {
	menu_id: string;
	parent_id?: string;
	name?: string;
	type?: number;
	perm_code?: string;
	path?: string;
	icon?: string;
	sort?: number;
	status?: number;
}

export interface MenusResp {
	menus: MenuItem[];
	perms: string[];
}

export interface MessageItem {
	message_id: string;
	user_id: string;
	title: string;
	content: string;
	is_read: boolean;
	biz_type: string;
	biz_id: string;
	created_at: number;
}

export interface MessageListReq {
	page: number;
	size: number;
	user_id?: string;
	only_unread?: boolean;
}

export interface MessageListResp {
	list: MessageItem[];
	total: number;
}

export interface NotifySettingItem {
	user_id: string;
	template_code: string;
	enabled: boolean;
	quiet_hours: string;
}

export interface NotifySettingListReq {
	user_id: string;
}

export interface NotifySettingListResp {
	list: NotifySettingItem[];
}

export interface NotifySettingUpsertReq {
	user_id?: string;
	template_code: string;
	enabled: boolean;
	quiet_hours?: string;
}

export interface OpportunityCreateReq {
	party_id: string;
	title: string;
	amount?: string;
	expected_close?: number;
	remark?: string;
}

export interface OpportunityItem {
	opportunity_id: string;
	party_id: string;
	party_name: string;
	title: string;
	stage: string;
	amount: string;
	expected_close: number;
	remark: string;
	created_at: number;
	updated_at: number;
}

export interface OpportunityListReq {
	page: number;
	size: number;
	party_id?: string;
	stage?: string;
	keyword?: string;
}

export interface OpportunityListResp {
	list: OpportunityItem[];
	total: number;
}

export interface OpportunityStageReq {
	id: string;
	stage: string;
}

export interface OrderCancelReq {
	order_no: string;
	reason?: string;
}

export interface OrderCreateReq {
	type: string;
	buyer_party_id?: string;
	remark?: string;
	items: OrderItemInputApi[];
	pay_timeout_minutes?: number;
}

export interface OrderCreateResp {
	order_id: string;
	order_no: string;
	total_amount: string;
	pay_expire_at: number;
	saga_id: string;
}

export interface OrderItemInputApi {
	sku_id: string;
	warehouse_id: string;
	qty: number;
	sn?: string;
}

export interface OrderItemView {
	item_id: string;
	sku_id: string;
	sku_name: string;
	sn: string;
	warehouse_id: string;
	qty: number;
	unit_price: string;
	amount: string;
	out_qty: number;
}

export interface OrderListReq {
	keyword?: string;
	type?: string;
	status?: string;
	page?: number;
	size?: number;
}

export interface OrderListResp {
	list: OrderView[];
	total: number;
}

export interface OrderNoPath {
	order_no: string;
}

export interface OrderPayReq {
	order_no: string;
	channel: string;
}

export interface OrderPayResp {
	payment_no: string;
	status: string;
	pay_params: string;
}

export interface OrderView {
	order_id: string;
	order_no: string;
	type: string;
	status: string;
	buyer_party_id: string;
	total_amount: string;
	pay_expire_at: number;
	paid_at: number;
	cancel_reason: string;
	remark: string;
	items: OrderItemView[];
	created_at: number;
	created_by: string;
}

export interface OrgCreateReq {
	parent_id?: string;
	name: string;
	sort?: number;
}

export interface OrgItem {
	org_id: string;
	parent_id: string;
	name: string;
	sort: number;
}

export interface OrgListResp {
	list: OrgItem[];
}

export interface OrgUpdateReq {
	org_id: string;
	parent_id?: string;
	name?: string;
	sort?: number;
}

export interface OtaDeviceView {
	id: string;
	device_id: string;
	sn: string;
	status: string;
	cmd_id: string;
	retry_count: number;
	error: string;
	dispatched_at: number;
	finished_at: number;
}

export interface OtaTaskCreateReq {
	name: string;
	product_key: string;
	firmware_id: string;
	rollback_firmware_id?: string;
	batch_size?: number;
	device_ids: string[];
}

export interface OtaTaskCreateResp {
	task_id: string;
}

export interface OtaTaskListReq {
	status?: string;
	product_key?: string;
	page?: number;
	size?: number;
}

export interface OtaTaskListResp {
	list: OtaTaskView[];
	total: number;
}

export interface OtaTaskNoPath {
	task_id: string;
}

export interface OtaTaskRollbackReq {
	task_id: string;
	reason?: string;
}

export interface OtaTaskRollbackResp {
	rolled_back: number;
}

export interface OtaTaskView {
	task_id: string;
	task_no: string;
	name: string;
	product_key: string;
	firmware_id: string;
	rollback_firmware_id: string;
	batch_size: number;
	fail_threshold_pct: number;
	status: string;
	total: number;
	success_count: number;
	fail_count: number;
	fail_reason: string;
	created_at: number;
	devices: OtaDeviceView[];
}

export interface PartyCreateReq {
	name: string;
	type: string[];
	credit_code?: string;
	region?: string;
	address?: string;
	remark?: string;
}

export interface PartyDetailResp {
	party: PartyItem;
}

export interface PartyItem {
	party_id: string;
	name: string;
	type: string[];
	status: number;
	credit_code: string;
	region: string;
	address: string;
	remark: string;
	created_at: number;
	updated_at: number;
}

export interface PartyListReq {
	page: number;
	size: number;
	keyword?: string;
	type?: string;
	status?: number;
}

export interface PartyListResp {
	list: PartyItem[];
	total: number;
}

export interface PartyUpdateReq {
	id: string;
	name: string;
	type: string[];
	status?: number;
	credit_code?: string;
	region?: string;
	address?: string;
	remark?: string;
}

export interface PaymentApproveReq {
	payment_no: string;
	approve: boolean;
	remark?: string;
}

export interface PaymentConfirmReq {
	payment_no: string;
	channel_txn_id?: string;
	paid_amount?: string;
	source?: string;
}

export interface PaymentListReq {
	keyword?: string;
	channel?: string;
	status?: string;
	page?: number;
	size?: number;
}

export interface PaymentListResp {
	list: PaymentView[];
	total: number;
}

export interface PaymentNoPath {
	payment_no: string;
}

export interface PaymentSettleReq {
	payment_no: string;
	remark?: string;
}

export interface PaymentView {
	payment_no: string;
	order_no: string;
	channel: string;
	status: string;
	amount: string;
	paid_amount: string;
	channel_txn_id: string;
	payer_party_id: string;
	created_by: string;
	approved_by: string;
	remark: string;
	paid_at: number;
	created_at: number;
}

export interface PriceItem {
	price_id: string;
	sku_id: string;
	price_type: string;
	tier_qty: number;
	amount: string;
	version: number;
	created_at: number;
}

export interface PriceListReq {
	sku_id: string;
	latest_only?: boolean;
}

export interface PriceListResp {
	list: PriceItem[];
	total: number;
}

export interface PriceSetReq {
	id: string;
	price_type: string;
	tier_qty?: number;
	amount: string;
}

export interface PriceSetResp {
	version: number;
}

export interface ProductCreateReq {
	name: string;
	category?: string;
	remark?: string;
}

export interface ProductItem {
	product_id: string;
	name: string;
	category: string;
	status: number;
	remark: string;
	created_at: number;
}

export interface ProductListReq {
	page: number;
	size: number;
	keyword?: string;
	status?: number;
}

export interface ProductListResp {
	list: ProductItem[];
	total: number;
}

export interface ReconcileListReq {
	status?: string;
	page?: number;
	size?: number;
}

export interface ReconcileListResp {
	list: ReconcileTaskView[];
	total: number;
}

export interface ReconcileResolveReq {
	id: number;
	resolution: string;
	remark?: string;
}

export interface ReconcileTaskView {
	task_id: string;
	task_no: string;
	type: string;
	biz_date: string;
	diff_report: string;
	status: string;
	resolution: string;
	resolve_remark: string;
	resolved_by: string;
	created_at: number;
}

export interface RefreshReq {
	refresh_token: string;
}

export interface RefreshResp {
	tokens: TokenPair;
}

export interface RefundCreateReq {
	payment_no: string;
	amount: string;
	return_no?: string;
	reason?: string;
}

export interface RefundCreateResp {
	refund_no: string;
	status: string;
}

export interface RefundListReq {
	keyword?: string;
	status?: string;
	page?: number;
	size?: number;
}

export interface RefundListResp {
	list: RefundView[];
	total: number;
}

export interface RefundView {
	refund_no: string;
	payment_no: string;
	order_no: string;
	return_no: string;
	amount: string;
	channel: string;
	status: string;
	channel_refund_id: string;
	reason: string;
	created_at: number;
}

export interface ReturnApproveReq {
	return_no: string;
	approve: boolean;
	remark?: string;
}

export interface ReturnCreateReq {
	order_no: string;
	items: ReturnItemInputApi[];
	reason?: string;
}

export interface ReturnCreateResp {
	return_id: string;
	return_no: string;
}

export interface ReturnItemInputApi {
	sku_id: string;
	qty: number;
	sn?: string;
	reason?: string;
}

export interface ReturnNoPath {
	return_no: string;
}

export interface RoleCreateReq {
	code: string;
	name: string;
	data_scope?: string;
	remark?: string;
	menu_ids?: string[];
}

export interface RoleDetailResp {
	role: RoleItem;
	menu_ids: string[];
}

export interface RoleItem {
	role_id: string;
	code: string;
	name: string;
	data_scope: string;
	remark: string;
	created_at: string;
}

export interface RoleListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface RoleListResp {
	list: RoleItem[];
	total: number;
}

export interface RoleUpdateReq {
	role_id: string;
	name?: string;
	data_scope?: string;
	remark?: string;
	menu_ids?: string[];
}

export interface SagaResp {
	saga: SagaView;
}

export interface SagaRetryReq {
	id: number;
	remark?: string;
}

export interface SagaStepView {
	step: number;
	name: string;
	status: string;
	idem_key: string;
}

export interface SagaView {
	saga_id: string;
	order_no: string;
	order_type: string;
	current_step: number;
	status: string;
	retry_count: number;
	next_retry_at: number;
	last_error: string;
	steps: SagaStepView[];
	updated_at: number;
}

export interface SalesSumReq {
	from?: number;
	to?: number;
}

export interface SalesSumResp {
	total_amount: string;
	order_count: number;
}

export interface SessionItem {
	sid: string;
	client: string;
	created_at: string;
}

export interface SessionKickReq {
	uid?: string;
	client?: string;
	sid?: string;
}

export interface SessionKickResp {
	kicked: number;
}

export interface SessionListReq {
	uid?: string;
	client?: string;
}

export interface SessionListResp {
	list: SessionItem[];
}

export interface ShipmentCreateReq {
	order_no: string;
	warehouse_id: string;
	items: ShipmentItemInputApi[];
	carrier?: string;
	tracking_no?: string;
}

export interface ShipmentCreateResp {
	shipment_id: string;
	shipment_no: string;
}

export interface ShipmentItemInputApi {
	sku_id: string;
	qty: number;
	sn?: string;
}

export interface ShipmentNoPath {
	shipment_no: string;
}

export interface ShipmentSignReq {
	shipment_no: string;
	signed_by: string;
}

export interface SimpleResp {
	uid?: string;
}

export interface SkuCreateReq {
	product_id: string;
	code: string;
	name: string;
	type?: string;
	spec?: string;
}

export interface SkuItem {
	sku_id: string;
	product_id: string;
	code: string;
	name: string;
	type: string;
	spec: string;
	status: number;
	created_at: number;
}

export interface SkuListReq {
	page: number;
	size: number;
	product_id?: string;
	keyword?: string;
}

export interface SkuListResp {
	list: SkuItem[];
	total: number;
}

export interface SlaBindReq {
	contract_no: string;
	strategy_id: string;
}

export interface SlaCreateReq {
	code: string;
	name: string;
	level: string;
	response_minutes: number;
	resolve_minutes: number;
}

export interface SlaCreateResp {
	strategy_id: string;
}

export interface SlaListResp {
	list: SlaStrategyView[];
}

export interface SlaStrategyView {
	strategy_id: string;
	code: string;
	name: string;
	level: string;
	response_minutes: number;
	resolve_minutes: number;
	created_at: number;
}

export interface StaffCreateReq {
	party_id: string;
	user_id?: string;
	name: string;
	staff_type?: string;
	skill_tags?: string[];
	work_region?: string;
}

export interface StaffItem {
	staff_id: string;
	party_id: string;
	user_id: string;
	name: string;
	staff_type: string;
	skill_tags: string[];
	work_region: string;
	status: number;
	created_at: number;
}

export interface StaffListResp {
	list: StaffItem[];
	total: number;
}

export interface StationBindItem {
	device_id?: string;
	sn?: string;
	role?: string;
}

export interface StationBindReq {
	station_id: string;
	devices: StationBindItem[];
	bound_by?: string;
}

export interface StationBindResp {
	bound: number;
}

export interface StationCreateReq {
	order_no?: string;
	station_no?: string;
	name: string;
	type: string;
	province?: string;
	city?: string;
	address?: string;
	longitude?: number;
	latitude?: number;
	capacity_kwh?: number;
	power_kw?: number;
	grid_status?: string;
	devices?: StationBindItem[];
}

export interface StationCreateResp {
	station_id: string;
}

export interface StationDeviceListResp {
	list: StationDeviceView[];
}

export interface StationDeviceView {
	id: string;
	station_id: string;
	device_id: string;
	sn: string;
	role: string;
	bound_at: number;
}

export interface StationGetResp {
	station: StationView;
}

export interface StationListReq {
	keyword?: string;
	status?: string;
	type?: string;
	page?: number;
	size?: number;
}

export interface StationListResp {
	list: StationView[];
	total: number;
}

export interface StationMonitorItem {
	device_id: string;
	sn: string;
	online: boolean;
	soc: number;
	power: number;
	voltage: number;
	temperature: number;
	ts: number;
}

export interface StationMonitorResp {
	station_id: string;
	device_count: number;
	online_count: number;
	avg_soc: number;
	total_power: number;
	items: StationMonitorItem[];
}

export interface StationNoPath {
	station_id: string;
}

export interface StationProductCreateReq {
	name: string;
	remark?: string;
	items: BomItem[];
}

export interface StationProductDetailResp {
	station_product: StationProductItem;
}

export interface StationProductItem {
	station_product_id: string;
	name: string;
	remark: string;
	items?: BomItem[];
	created_at: number;
}

export interface StationProductListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface StationProductListResp {
	list: StationProductItem[];
	total: number;
}

export interface StationStaffAddReq {
	station_id: string;
	user_id: string;
	staff_type: string;
	shift?: string;
}

export interface StationStaffListResp {
	list: StationStaffView[];
}

export interface StationStaffRemoveReq {
	station_id: string;
	user_id: string;
}

export interface StationStaffView {
	id: string;
	station_id: string;
	user_id: string;
	staff_type: string;
	shift: string;
	created_at: number;
}

export interface StationTopologyResp {
	topology: StationTopologyView;
}

export interface StationTopologySaveReq {
	station_id: string;
	nodes_json: string;
	edges_json: string;
}

export interface StationTopologySaveResp {
	version: number;
}

export interface StationTopologyView {
	version: number;
	nodes_json: string;
	edges_json: string;
	updated_at: number;
}

export interface StationView {
	station_id: string;
	station_no: string;
	name: string;
	type: string;
	status: string;
	province: string;
	city: string;
	address: string;
	longitude: number;
	latitude: number;
	capacity_kwh: number;
	power_kw: number;
	grid_status: string;
	order_no: string;
	created_at: number;
}

export interface StepUpReq {
	password: string;
}

export interface StepUpResp {
	level: number;
	access_token: string;
	access_expires_in: number;
}

export interface StockOpReq {
	warehouse_id: string;
	sku_id: string;
	qty: number;
	biz_type?: string;
	biz_no?: string;
	remark?: string;
}

export interface StockOpResp {
	record_id: string;
}

export interface StockRecordItem {
	record_id: string;
	inventory_id: string;
	warehouse_id: string;
	sku_id: string;
	biz_type: string;
	biz_no: string;
	qty: number;
	before_available: number;
	after_available: number;
	before_locked: number;
	after_locked: number;
	remark: string;
	created_at: number;
}

export interface StockRecordListReq {
	page: number;
	size: number;
	warehouse_id?: string;
	sku_id?: string;
	biz_type?: string;
}

export interface StockRecordListResp {
	list: StockRecordItem[];
	total: number;
}

export interface StocktakeApproveReq {
	id: string;
	approve: boolean;
	remark?: string;
}

export interface StocktakeCreateReq {
	warehouse_id: string;
	remark?: string;
}

export interface StocktakeDetailResp {
	stocktake: StocktakeRecord;
}

export interface StocktakeItem {
	item_id: string;
	sku_id: string;
	book_qty: number;
	counted_qty: number;
	diff_qty: number;
}

export interface StocktakeListReq {
	page: number;
	size: number;
	warehouse_id?: string;
	status?: number;
}

export interface StocktakeListResp {
	list: StocktakeRecord[];
	total: number;
}

export interface StocktakeRecord {
	stocktake_id: string;
	warehouse_id: string;
	status: number;
	remark: string;
	items?: StocktakeItem[];
	created_at: number;
}

export interface StocktakeSubmitItem {
	sku_id: string;
	counted_qty: number;
}

export interface StocktakeSubmitReq {
	id: string;
	items: StocktakeSubmitItem[];
}

export interface TemplateItem {
	template_id: string;
	code: string;
	title_template: string;
	content_template: string;
	channel: string;
	status: number;
}

export interface TemplateListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface TemplateListResp {
	list: TemplateItem[];
	total: number;
}

export interface TemplateUpsertReq {
	code: string;
	title_template: string;
	content_template: string;
	channel?: string;
	status?: number;
}

export interface TenantCreateReq {
	tenant_code: string;
	name: string;
	plan?: string;
	quota?: string;
}

export interface TenantItem {
	tenant_id: string;
	tenant_code: string;
	name: string;
	plan: string;
	quota: string;
	status: number;
}

export interface TenantListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface TenantListResp {
	list: TenantItem[];
	total: number;
}

export interface TenantQuotaReq {
	tenant_id: string;
	quota: string;
}

export interface TenantUpdateReq {
	tenant_id: string;
	name?: string;
	plan?: string;
	status?: number;
}

export interface TokenPair {
	access_token: string;
	refresh_token: string;
	access_expires_in: number;
	refresh_expires_in: number;
}

export interface TraceAddReq {
	shipment_no: string;
	node: string;
	description?: string;
	trace_time?: number;
}

export interface UnreadCountResp {
	count: number;
}

export interface UserCreateReq {
	nickname: string;
	mobile: string;
	email?: string;
	password: string;
	types: string[];
	org_id?: string;
	role_ids?: string[];
}

export interface UserItem {
	uid: string;
	org_id: string;
	party_id: string;
	nickname: string;
	mobile_masked: string;
	email_masked: string;
	types: string[];
	status: number;
	locked_until: string;
	role_codes: string[];
	created_at: string;
}

export interface UserListReq {
	page: number;
	size: number;
	keyword?: string;
	status?: number;
}

export interface UserListResp {
	list: UserItem[];
	total: number;
}

export interface UserPasswordReq {
	uid: string;
	new_password: string;
}

export interface UserStatusReq {
	uid: string;
	status: number;
}

export interface UserUpdateReq {
	uid: string;
	nickname?: string;
	mobile?: string;
	email?: string;
	types?: string[];
	org_id?: string;
	role_ids?: string[];
}

export interface WarehouseCreateReq {
	code: string;
	name: string;
	address?: string;
}

export interface WarehouseItem {
	warehouse_id: string;
	code: string;
	name: string;
	address: string;
	status: number;
	created_at: number;
}

export interface WarehouseListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface WarehouseListResp {
	list: WarehouseItem[];
	total: number;
}

export interface WarrantyListReq {
	status?: string;
	level?: string;
	page?: number;
	size?: number;
}

export interface WarrantyListResp {
	list: WarrantyView[];
	total: number;
}

export interface WarrantyPolicyItem {
	sku_id: string;
	period_months: number;
	start_rule: string;
}

export interface WarrantyPolicyUpsertReq {
	id: string;
	period_months: number;
	start_rule: string;
}

export interface WarrantyTargetReq {
	target_type: string;
	target_id?: string;
	sn?: string;
}

export interface WarrantyTargetResp {
	list: WarrantyView[];
}

export interface WarrantyView {
	warranty_no: string;
	level: string;
	target_type: string;
	target_id: string;
	target_key: string;
	status: string;
	start_at: number;
	end_at: number;
	months: number;
	start_rule: string;
	source_type: string;
	source_no: string;
	created_at: number;
}

