// Code generated by tools/apitypes from .api contract. DO NOT EDIT.
// 生成物入库（CI diff 阻断，02 §12.5）；改契约 → 重生成 → diff 干净。

export interface IDPath {
	id: string;
}

export interface LoginReq {
	mobile: string;
	password: string;
}

export interface LoginResp {
	tokens: TokenPair;
	uid: string;
	nickname: string;
}

export interface MeResp {
	uid: string;
	nickname: string;
	mobile: string;
	tenant_id: string;
	roles: string[];
	perms: string[];
	data_scope: string;
}

export interface MenuCreateReq {
	parent_id?: string;
	name: string;
	type: number;
	perm_code?: string;
	path?: string;
	icon?: string;
	sort?: number;
}

export interface MenuItem {
	menu_id: string;
	parent_id: string;
	name: string;
	type: number;
	perm_code: string;
	path: string;
	icon: string;
	sort: number;
	status: number;
}

export interface MenuListResp {
	list: MenuItem[];
}

export interface MenuUpdateReq {
	menu_id: string;
	parent_id?: string;
	name?: string;
	type?: number;
	perm_code?: string;
	path?: string;
	icon?: string;
	sort?: number;
	status?: number;
}

export interface MenusResp {
	menus: MenuItem[];
	perms: string[];
}

export interface OrgCreateReq {
	parent_id?: string;
	name: string;
	sort?: number;
}

export interface OrgItem {
	org_id: string;
	parent_id: string;
	name: string;
	sort: number;
}

export interface OrgListResp {
	list: OrgItem[];
}

export interface OrgUpdateReq {
	org_id: string;
	parent_id?: string;
	name?: string;
	sort?: number;
}

export interface RefreshReq {
	refresh_token: string;
}

export interface RefreshResp {
	tokens: TokenPair;
}

export interface RoleCreateReq {
	code: string;
	name: string;
	data_scope?: string;
	remark?: string;
	menu_ids?: string[];
}

export interface RoleDetailResp {
	role: RoleItem;
	menu_ids: string[];
}

export interface RoleItem {
	role_id: string;
	code: string;
	name: string;
	data_scope: string;
	remark: string;
	created_at: string;
}

export interface RoleListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface RoleListResp {
	list: RoleItem[];
	total: number;
}

export interface RoleUpdateReq {
	role_id: string;
	name?: string;
	data_scope?: string;
	remark?: string;
	menu_ids?: string[];
}

export interface SessionItem {
	sid: string;
	client: string;
	created_at: string;
}

export interface SessionKickReq {
	uid?: string;
	client?: string;
	sid?: string;
}

export interface SessionKickResp {
	kicked: number;
}

export interface SessionListReq {
	uid?: string;
	client?: string;
}

export interface SessionListResp {
	list: SessionItem[];
}

export interface SimpleResp {
	uid?: string;
}

export interface StepUpReq {
	password: string;
}

export interface StepUpResp {
	level: number;
	access_token: string;
	access_expires_in: number;
}

export interface TenantCreateReq {
	tenant_code: string;
	name: string;
	plan?: string;
	quota?: string;
}

export interface TenantItem {
	tenant_id: string;
	tenant_code: string;
	name: string;
	plan: string;
	quota: string;
	status: number;
}

export interface TenantListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface TenantListResp {
	list: TenantItem[];
	total: number;
}

export interface TenantQuotaReq {
	tenant_id: string;
	quota: string;
}

export interface TenantUpdateReq {
	tenant_id: string;
	name?: string;
	plan?: string;
	status?: number;
}

export interface TokenPair {
	access_token: string;
	refresh_token: string;
	access_expires_in: number;
	refresh_expires_in: number;
}

export interface UserCreateReq {
	nickname: string;
	mobile: string;
	email?: string;
	password: string;
	types: string[];
	org_id?: string;
	role_ids?: string[];
}

export interface UserItem {
	uid: string;
	org_id: string;
	party_id: string;
	nickname: string;
	mobile_masked: string;
	email_masked: string;
	types: string[];
	status: number;
	locked_until: string;
	role_codes: string[];
	created_at: string;
}

export interface UserListReq {
	page: number;
	size: number;
	keyword?: string;
	status?: number;
}

export interface UserListResp {
	list: UserItem[];
	total: number;
}

export interface UserPasswordReq {
	uid: string;
	new_password: string;
}

export interface UserStatusReq {
	uid: string;
	status: number;
}

export interface UserUpdateReq {
	uid: string;
	nickname?: string;
	mobile?: string;
	email?: string;
	types?: string[];
	org_id?: string;
	role_ids?: string[];
}

