// Code generated by tools/apitypes from .api contract. DO NOT EDIT.
// 生成物入库（CI diff 阻断，02 §12.5）；改契约 → 重生成 → diff 干净。

export interface AuditLogItem {
	log_id: string;
	trace_id: string;
	uid: string;
	action: string;
	target_type: string;
	target_id: string;
	before_json: string;
	after_json: string;
	result: string;
	client: string;
	on_behalf_of: string;
	created_at: number;
}

export interface AuditLogListReq {
	page: number;
	size: number;
	action?: string;
	uid?: string;
	target_type?: string;
	target_id?: string;
}

export interface AuditLogListResp {
	list: AuditLogItem[];
	total: number;
}

export interface BomItem {
	sku_id: string;
	sku_name: string;
	qty: number;
}

export interface CmdAuditItem {
	cmd_audit_id: string;
	cmd_id: string;
	sn: string;
	uid: string;
	action: string;
	payload_json: string;
	result: string;
	error: string;
	trace_id: string;
	created_at: number;
}

export interface CmdAuditListReq {
	page: number;
	size: number;
	sn?: string;
	cmd_id?: string;
}

export interface CmdAuditListResp {
	list: CmdAuditItem[];
	total: number;
}

export interface ContactCreateReq {
	id: string;
	name: string;
	mobile: string;
	position?: string;
	is_default?: boolean;
	notify_pref?: string;
}

export interface ContactItem {
	contact_id: string;
	party_id: string;
	name: string;
	mobile: string;
	position: string;
	is_default: boolean;
	notify_pref: string;
	created_at: number;
}

export interface ContactListResp {
	list: ContactItem[];
}

export interface CrmRecordCreateReq {
	id: string;
	content: string;
	next_follow_at?: number;
}

export interface CrmRecordItem {
	record_id: string;
	party_id: string;
	content: string;
	next_follow_at: number;
	created_by: string;
	created_at: number;
}

export interface CrmRecordListResp {
	list: CrmRecordItem[];
}

export interface DealerExtItem {
	party_id: string;
	dealer_level: string;
	authorized_region: string;
	rebate_rule: string;
	updated_at: number;
}

export interface DealerExtResp {
	dealer_ext: DealerExtItem;
}

export interface DealerExtUpsertReq {
	id: string;
	dealer_level?: string;
	authorized_region?: string;
	rebate_rule?: string;
}

export interface IDPath {
	id: string;
}

export interface InventoryItem {
	inventory_id: string;
	warehouse_id: string;
	sku_id: string;
	available: number;
	locked: number;
	in_transit: number;
	defective: number;
	low_stock_threshold: number;
	updated_at: number;
}

export interface InventoryListReq {
	page: number;
	size: number;
	warehouse_id?: string;
	sku_id?: string;
	low_only?: boolean;
}

export interface InventoryListResp {
	list: InventoryItem[];
	total: number;
}

export interface LoginReq {
	mobile: string;
	password: string;
}

export interface LoginResp {
	tokens: TokenPair;
	uid: string;
	nickname: string;
}

export interface MeResp {
	uid: string;
	nickname: string;
	mobile: string;
	tenant_id: string;
	roles: string[];
	perms: string[];
	data_scope: string;
}

export interface MenuCreateReq {
	parent_id?: string;
	name: string;
	type: number;
	perm_code?: string;
	path?: string;
	icon?: string;
	sort?: number;
}

export interface MenuItem {
	menu_id: string;
	parent_id: string;
	name: string;
	type: number;
	perm_code: string;
	path: string;
	icon: string;
	sort: number;
	status: number;
}

export interface MenuListResp {
	list: MenuItem[];
}

export interface MenuUpdateReq {
	menu_id: string;
	parent_id?: string;
	name?: string;
	type?: number;
	perm_code?: string;
	path?: string;
	icon?: string;
	sort?: number;
	status?: number;
}

export interface MenusResp {
	menus: MenuItem[];
	perms: string[];
}

export interface MessageItem {
	message_id: string;
	user_id: string;
	title: string;
	content: string;
	is_read: boolean;
	biz_type: string;
	biz_id: string;
	created_at: number;
}

export interface MessageListReq {
	page: number;
	size: number;
	user_id?: string;
	only_unread?: boolean;
}

export interface MessageListResp {
	list: MessageItem[];
	total: number;
}

export interface NotifySettingItem {
	user_id: string;
	template_code: string;
	enabled: boolean;
	quiet_hours: string;
}

export interface NotifySettingListReq {
	user_id: string;
}

export interface NotifySettingListResp {
	list: NotifySettingItem[];
}

export interface NotifySettingUpsertReq {
	user_id?: string;
	template_code: string;
	enabled: boolean;
	quiet_hours?: string;
}

export interface OpportunityCreateReq {
	party_id: string;
	title: string;
	amount?: string;
	expected_close?: number;
	remark?: string;
}

export interface OpportunityItem {
	opportunity_id: string;
	party_id: string;
	party_name: string;
	title: string;
	stage: string;
	amount: string;
	expected_close: number;
	remark: string;
	created_at: number;
	updated_at: number;
}

export interface OpportunityListReq {
	page: number;
	size: number;
	party_id?: string;
	stage?: string;
	keyword?: string;
}

export interface OpportunityListResp {
	list: OpportunityItem[];
	total: number;
}

export interface OpportunityStageReq {
	id: string;
	stage: string;
}

export interface OrgCreateReq {
	parent_id?: string;
	name: string;
	sort?: number;
}

export interface OrgItem {
	org_id: string;
	parent_id: string;
	name: string;
	sort: number;
}

export interface OrgListResp {
	list: OrgItem[];
}

export interface OrgUpdateReq {
	org_id: string;
	parent_id?: string;
	name?: string;
	sort?: number;
}

export interface PartyCreateReq {
	name: string;
	type: string[];
	credit_code?: string;
	region?: string;
	address?: string;
	remark?: string;
}

export interface PartyDetailResp {
	party: PartyItem;
}

export interface PartyItem {
	party_id: string;
	name: string;
	type: string[];
	status: number;
	credit_code: string;
	region: string;
	address: string;
	remark: string;
	created_at: number;
	updated_at: number;
}

export interface PartyListReq {
	page: number;
	size: number;
	keyword?: string;
	type?: string;
	status?: number;
}

export interface PartyListResp {
	list: PartyItem[];
	total: number;
}

export interface PartyUpdateReq {
	id: string;
	name: string;
	type: string[];
	status?: number;
	credit_code?: string;
	region?: string;
	address?: string;
	remark?: string;
}

export interface PriceItem {
	price_id: string;
	sku_id: string;
	price_type: string;
	tier_qty: number;
	amount: string;
	version: number;
	created_at: number;
}

export interface PriceListReq {
	sku_id: string;
	latest_only?: boolean;
}

export interface PriceListResp {
	list: PriceItem[];
	total: number;
}

export interface PriceSetReq {
	id: string;
	price_type: string;
	tier_qty?: number;
	amount: string;
}

export interface PriceSetResp {
	version: number;
}

export interface ProductCreateReq {
	name: string;
	category?: string;
	remark?: string;
}

export interface ProductItem {
	product_id: string;
	name: string;
	category: string;
	status: number;
	remark: string;
	created_at: number;
}

export interface ProductListReq {
	page: number;
	size: number;
	keyword?: string;
	status?: number;
}

export interface ProductListResp {
	list: ProductItem[];
	total: number;
}

export interface RefreshReq {
	refresh_token: string;
}

export interface RefreshResp {
	tokens: TokenPair;
}

export interface RoleCreateReq {
	code: string;
	name: string;
	data_scope?: string;
	remark?: string;
	menu_ids?: string[];
}

export interface RoleDetailResp {
	role: RoleItem;
	menu_ids: string[];
}

export interface RoleItem {
	role_id: string;
	code: string;
	name: string;
	data_scope: string;
	remark: string;
	created_at: string;
}

export interface RoleListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface RoleListResp {
	list: RoleItem[];
	total: number;
}

export interface RoleUpdateReq {
	role_id: string;
	name?: string;
	data_scope?: string;
	remark?: string;
	menu_ids?: string[];
}

export interface SessionItem {
	sid: string;
	client: string;
	created_at: string;
}

export interface SessionKickReq {
	uid?: string;
	client?: string;
	sid?: string;
}

export interface SessionKickResp {
	kicked: number;
}

export interface SessionListReq {
	uid?: string;
	client?: string;
}

export interface SessionListResp {
	list: SessionItem[];
}

export interface SimpleResp {
	uid?: string;
}

export interface SkuCreateReq {
	product_id: string;
	code: string;
	name: string;
	type?: string;
	spec?: string;
}

export interface SkuItem {
	sku_id: string;
	product_id: string;
	code: string;
	name: string;
	type: string;
	spec: string;
	status: number;
	created_at: number;
}

export interface SkuListReq {
	page: number;
	size: number;
	product_id?: string;
	keyword?: string;
}

export interface SkuListResp {
	list: SkuItem[];
	total: number;
}

export interface StaffCreateReq {
	party_id: string;
	user_id?: string;
	name: string;
	staff_type?: string;
	skill_tags?: string[];
	work_region?: string;
}

export interface StaffItem {
	staff_id: string;
	party_id: string;
	user_id: string;
	name: string;
	staff_type: string;
	skill_tags: string[];
	work_region: string;
	status: number;
	created_at: number;
}

export interface StaffListResp {
	list: StaffItem[];
	total: number;
}

export interface StationProductCreateReq {
	name: string;
	remark?: string;
	items: BomItem[];
}

export interface StationProductDetailResp {
	station_product: StationProductItem;
}

export interface StationProductItem {
	station_product_id: string;
	name: string;
	remark: string;
	items?: BomItem[];
	created_at: number;
}

export interface StationProductListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface StationProductListResp {
	list: StationProductItem[];
	total: number;
}

export interface StepUpReq {
	password: string;
}

export interface StepUpResp {
	level: number;
	access_token: string;
	access_expires_in: number;
}

export interface StockOpReq {
	warehouse_id: string;
	sku_id: string;
	qty: number;
	biz_type?: string;
	biz_no?: string;
	remark?: string;
}

export interface StockOpResp {
	record_id: string;
}

export interface StockRecordItem {
	record_id: string;
	inventory_id: string;
	warehouse_id: string;
	sku_id: string;
	biz_type: string;
	biz_no: string;
	qty: number;
	before_available: number;
	after_available: number;
	before_locked: number;
	after_locked: number;
	remark: string;
	created_at: number;
}

export interface StockRecordListReq {
	page: number;
	size: number;
	warehouse_id?: string;
	sku_id?: string;
	biz_type?: string;
}

export interface StockRecordListResp {
	list: StockRecordItem[];
	total: number;
}

export interface StocktakeApproveReq {
	id: string;
	approve: boolean;
	remark?: string;
}

export interface StocktakeCreateReq {
	warehouse_id: string;
	remark?: string;
}

export interface StocktakeDetailResp {
	stocktake: StocktakeRecord;
}

export interface StocktakeItem {
	item_id: string;
	sku_id: string;
	book_qty: number;
	counted_qty: number;
	diff_qty: number;
}

export interface StocktakeListReq {
	page: number;
	size: number;
	warehouse_id?: string;
	status?: number;
}

export interface StocktakeListResp {
	list: StocktakeRecord[];
	total: number;
}

export interface StocktakeRecord {
	stocktake_id: string;
	warehouse_id: string;
	status: number;
	remark: string;
	items?: StocktakeItem[];
	created_at: number;
}

export interface StocktakeSubmitItem {
	sku_id: string;
	counted_qty: number;
}

export interface StocktakeSubmitReq {
	id: string;
	items: StocktakeSubmitItem[];
}

export interface TemplateItem {
	template_id: string;
	code: string;
	title_template: string;
	content_template: string;
	channel: string;
	status: number;
}

export interface TemplateListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface TemplateListResp {
	list: TemplateItem[];
	total: number;
}

export interface TemplateUpsertReq {
	code: string;
	title_template: string;
	content_template: string;
	channel?: string;
	status?: number;
}

export interface TenantCreateReq {
	tenant_code: string;
	name: string;
	plan?: string;
	quota?: string;
}

export interface TenantItem {
	tenant_id: string;
	tenant_code: string;
	name: string;
	plan: string;
	quota: string;
	status: number;
}

export interface TenantListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface TenantListResp {
	list: TenantItem[];
	total: number;
}

export interface TenantQuotaReq {
	tenant_id: string;
	quota: string;
}

export interface TenantUpdateReq {
	tenant_id: string;
	name?: string;
	plan?: string;
	status?: number;
}

export interface TokenPair {
	access_token: string;
	refresh_token: string;
	access_expires_in: number;
	refresh_expires_in: number;
}

export interface UnreadCountResp {
	count: number;
}

export interface UserCreateReq {
	nickname: string;
	mobile: string;
	email?: string;
	password: string;
	types: string[];
	org_id?: string;
	role_ids?: string[];
}

export interface UserItem {
	uid: string;
	org_id: string;
	party_id: string;
	nickname: string;
	mobile_masked: string;
	email_masked: string;
	types: string[];
	status: number;
	locked_until: string;
	role_codes: string[];
	created_at: string;
}

export interface UserListReq {
	page: number;
	size: number;
	keyword?: string;
	status?: number;
}

export interface UserListResp {
	list: UserItem[];
	total: number;
}

export interface UserPasswordReq {
	uid: string;
	new_password: string;
}

export interface UserStatusReq {
	uid: string;
	status: number;
}

export interface UserUpdateReq {
	uid: string;
	nickname?: string;
	mobile?: string;
	email?: string;
	types?: string[];
	org_id?: string;
	role_ids?: string[];
}

export interface WarehouseCreateReq {
	code: string;
	name: string;
	address?: string;
}

export interface WarehouseItem {
	warehouse_id: string;
	code: string;
	name: string;
	address: string;
	status: number;
	created_at: number;
}

export interface WarehouseListReq {
	page: number;
	size: number;
	keyword?: string;
}

export interface WarehouseListResp {
	list: WarehouseItem[];
	total: number;
}

export interface WarrantyPolicyItem {
	sku_id: string;
	period_months: number;
	start_rule: string;
}

export interface WarrantyPolicyUpsertReq {
	id: string;
	period_months: number;
	start_rule: string;
}

